# PhantomArch — Hyprpaper (Wallpaper) Configuration

preload = /usr/share/phantom/wallpapers/phantom-cyberpunk-default.png
preload = /usr/share/phantom/wallpapers/phantom-neon-grid.png
preload = /usr/share/phantom/wallpapers/phantom-ghost-machine.png

wallpaper = ,/usr/share/phantom/wallpapers/phantom-cyberpunk-default.png

splash = false
ipc = on
