[General]
InputMethod=
Numlock=on

[Theme]
Current=phantom-v3
CursorTheme=Bibata-Modern-Classic
CursorSize=24

[Users]
MaximumUid=60513
MinimumUid=1000
RememberLastUser=true
RememberLastSession=true

[Wayland]
SessionDir=/usr/share/wayland-sessions
EnableHiDPI=true

[X11]
SessionDir=/usr/share/xsessions
