title   PhantomArch (linux-zen)
linux   /arch/boot/x86_64/vmlinuz-linux-zen
initrd  /arch/boot/x86_64/initramfs-linux-zen.img
options archisobasedir=arch archisosearchuuid=%ARCHISO_UUID% quiet splash loglevel=3 nowatchdog
